### ISSUE TITLE
Feature request: Nuxt support

### ISSUE THREAD

**Issue by Demivan** [fluent-vue/fluent-vue#695]
Nuxt 2:
- [x] Build module:
repo: https://github.com/fluent-vue/nuxt2-build-module#readme
npm: https://www.npmjs.com/package/@fluent-vue/nuxt2-build-module
- [x] WIP: Update directive SSR code to support parameters and modifiers

Nuxt 3:
- [x] Build module

Common?:
- [x] Create a package for directive SSR support
- [ ] ~~Reimplement `@nuxtjs/i18n` for `fluent-vue`. Probably when `@nuxt/i18n` is updated to Nuxt 3~~ Scope is too big

**Comment by Demivan** [comment]
I will be starting on it tomorrow. I was busy with my main job, so didn't have time to work on it before.
@reemhamz Are you planning to use Nuxt 2 or 3?

**Comment by Demivan** [comment]
I have added a simple Nuxt 2 example: https://github.com/fluent-vue/examples/tree/main/nuxt-2

Implementing something like https://github.com/nuxt-community/i18n-module will take much more time. I'd rather work on making `v-t` directive compatible with SSR for now. When Nuxt 3 is stable I should be able to use nuxt-kit to implement analog of i18n-module that is Nuxt 2 and Nuxt 3 compatible.

**Comment by 0xMANFRE** [comment]
> Reimplement @nuxtjs/i18n for fluent-vue. Probably when @nuxt/i18n is updated to Nuxt 3

@Demivan is the Nuxt 3 module still worked on?
The pluralisation syntax of `vue-i18n` and `@nuxtjs/i18n` is terrible and has zero flexibility compared to Fluent or even MessageFormat.
I would love to switch to a future `@nuxtjs/fluent` or `@fluent-vue/nuxt` when it will become available.

**Comment by Demivan** [comment]
@0xMANFRE `@nuxtjs/i18n` is huge and has lots of features. It will be few times bigger than `fluent-vue` itself. I don't have time to reimplement everything.
But basic integration of `fluent-vue` into `Nuxt` is easy. You add `unplugin-fluent-vue` plugin and add a `Nuxt` plugin that initialized `fluent-vue`. Code is already SSR compatible.

**Comment by Demivan** [comment]
By the way, I plan to support MessageFormat 4 when the syntax is finalized.

**Comment by 0xMANFRE** [comment]
> But basic integration of `fluent-vue` into `Nuxt` is easy. You add `unplugin-fluent-vue` Vite plugin and create a custom `Nuxt` plugin that initializes `fluent-vue`. Code is SSR compatible already.

The documentation provides only a Vite config file.
Is there a working Vue 3 example that has external locale files and a locale switcher? I can't seem to find it.

**Comment by Demivan** [comment]
There is no `Nuxt` 3 example. I will create it and link it here.

**Comment by Demivan** [comment]
Added Nuxt 3 example https://github.com/fluent-vue/examples/tree/main/nuxt-3. Check the `plugins` and `modules` folders for implementation. You still need some way of selecting the current locale on the server, but that really depends on your site (is it per domain, path or read from cookie) 

What is not working is SSR for the `v-t` directive. I almost never use it, but I will work on the SSR implementation this week.
