### ISSUE TITLE
custom warn function

### ISSUE THREAD

**Issue by markmartirosian** [fluent-vue/fluent-vue#779]
**Is your feature request related to a problem? Please describe.**

`console.warn` pollutes log output in containerized SSR application.

**Describe the solution you'd like**

A `warn` configuration option.

**Comment by Demivan** [comment]
There should not be a warning in production.

https://github.com/fluent-vue/fluent-vue/blob/02e6d869d280cb1bc7e809218054d0b74fe9ecde/src/util/warn.ts#L7-L8

Or you want to disable it in development too?

**Comment by Demivan** [comment]
@markmartirosian Check if #780 implements all that you need.

**Comment by markmartirosian** [comment]
@Demivan I think it does, thanks a lot!

**Comment by Demivan** [comment]
Published v3.1.0 with this feature
