### ISSUE TITLE
Remove bom from files

### ISSUE THREAD

**Issue by hulpak** [fluent-vue/fluent-vue#800]
### Describe the bug

On the ftl files add specific symbol before translations which break the right translation

### System Info

```Shell
--browsers
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/fluent-vue/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guide](https://github.com/fluent-vue/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
This should not be needed with Vite 4
