### ISSUE TITLE
Migration path from vue-i18n to fluent-vue

### ISSUE THREAD

**Issue by Flambe** [fluent-vue/fluent-vue#805]
### Clear and concise description of the problem

I'm looking to move from vue-i18n to this library. We already use vue-i18n quite extensively throughout our app so it'd be nice to have both libraries installed together to slowly convert everything to fluent.

My problem is that we're using `$t` from vue-i18n throughout our app which conflicts with the same function from fluent-vue meaning we'd have to spend a lot of time to convert everyone in one go.

### Suggested solution

Maybe a way to rename the globals or a flag that that does this for you? It would be fairly easy to find and replace over the app to switch it back once everything was migrated.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/fluent-vue/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/fluent-vue/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Demivan** [comment]
It would be a nice feature to have. Do you want to contribute? If not, I will fix it on an hour or so, when electricity is back on.

Only need to change the install function. Add a new option with names of component, directive and global functions to it.

**Comment by Flambe** [comment]
I haven't played around with vue plugins before but I'll give it a go! I am finishing for the day soon though so it's unlikely I'll have anything ready to go before I leave.

**Comment by Demivan** [comment]
You don't need to update component name there. It is only used for debugging in devtools.

**Comment by Demivan** [comment]
This feature was released as part of v3.3.0 https://github.com/fluent-vue/fluent-vue/releases/tag/v3.3.0
