### ISSUE TITLE
Help with Fluent Bundles

### ISSUE THREAD

**Issue by Ericlm** [fluent-vue/fluent-vue#810]
Hello there! I'm totally new to fluent-vue, and I wanted to know a few things that I couldn't find in the docs : 
- how does the `bundles` property affect the order in which messages are applied (like fallbacks) ?
- how can I automatically set the right bundles for the navigator language, especially if I want something like `fr-FR` => if message not found `fr` => if message not found `en` ?

Thank you for your help!

**Comment by Demivan** [comment]
> how does the bundles property affect the order in which messages are applied (like fallback) ?

Yes. List of bundles works like fallback. If message if not found it first bundle, it is searched in the next one.

> how can I automatically set the right bundles for the navigator language, especially if I want something like fr-FR => if message not found fr => if message not found en ?

Language negotiation depends on your app logic, that is why it is not a part of `fluent-vue`. `fluent-vue` only cares about order of bundles that are passed to it.

Here is the example from one of my projects:

```ts
const bundles = {
  'en-GB': new FluentBundle('en-GB'),
  'da-DK': new FluentBundle('da-DK'),
  'nb-NO': new FluentBundle('nb-NO'),
  'sv-SE': new FluentBundle('sv-SE'),
}

function getBundlesForLocale(locale: string) {
  switch (locale) {
    case 'en-GB': return [bundles['en-GB']]
    case 'da-DK': return [bundles['da-DK'], bundles['en-GB']]
    case 'nb-NO': return [bundles['nb-NO'], bundles['da-DK'], bundles['en-GB']]
    case 'sv-SE': return [bundles['sv-SE'], bundles['da-DK'], bundles['en-GB']]
    default: return [bundles['en-GB']]
  }
}

export function changeLocale(locale: string) {
  fluent.bundles = getBundlesForLocale(locale)
}
```

As we only have 4 supported and localized languages, this logic is enough for us.

If you need more complex logic you can use [@fluent/langneg](https://github.com/projectfluent/fluent.js/tree/master/fluent-langneg) to get and an array of supported languages. And from that you can get an array of bundles that you actually have translated.

**Comment by Ericlm** [comment]
Thank you very much for the detailed answer! And for the framework, it seems much more flexible than vue-i18n 😀

**Comment by Demivan** [comment]
You are welcome. That was the idea - to be more flexible and easier to use for developers than `vue-i18n` 🙂
