### ISSUE TITLE
Lazyloading .flt files

### ISSUE THREAD

**Issue by quanghm27** [fluent-vue/fluent-vue#815]
Hi @Demivan,
Thank you for bringing a good library 👍
I walked through the docs and see that no section/example for lazyloading .flt resources.
Would you mind adding it?

**Comment by Demivan** [comment]
Hi, thanks for kind words.

Yeah, it would be nice to add something for tis.
Will something like this https://github.com/orgs/fluent-vue/discussions/783 work for you?

**Comment by quanghm27** [comment]
awesome, i forgot to search in discussions 😄

**Comment by Demivan** [comment]
@quanghm27 No problem. I still need to add it to docs :slightly_smiling_face:

**Comment by quanghm27** [comment]
Yeah, ppl will love this section.
Have a nice day!
