### ISSUE TITLE
How to disable BiDi in fluent?

### ISSUE THREAD

**Issue by Tnze** [fluent-vue/fluent-vue#843]
### Clear and concise description of the problem

In my project [BestCraft](https://github.com/Tnze/ffxiv-best-craft), there is a feature that copy a translated message to the system's clipboard, allows the user to paste it to the game.

Unfortunately, the game fail to handle the Unicode BDI/FSI control codes `U+2068` and `U+2069`.
Is there a way to disable the feature?

links:

### Suggested solution

Having an option to disable BDI/FSI control codes insertion.

### Alternative

May I can use a regular expression to filter out these characters? I don't know how.
But obviously, this is less elegant.

### Additional context

<https://github.com/projectfluent/fluent/wiki/Fluent-and-ICU-MessageFormat#bidi>
<http://unicode.org/reports/tr9/#Directional_Formatting_Characters>
<https://github.com/projectfluent/fluent/wiki/BiDi-in-Fluent>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/fluent-vue/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/fluent-vue/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Tnze** [comment]
For example:

This is the message to be copied:
![image](https://github.com/fluent-vue/fluent-vue/assets/19628575/22faebfd-0266-4ca8-9e8f-d922403b92f0)

But when I paste it to VSCode:
![image](https://github.com/fluent-vue/fluent-vue/assets/19628575/af755a74-7992-4f0f-94fb-7a29b727d1cd)

When the translations are not used for directly displayed in browser, we need a way to avoid having these beautiful chars.

**Comment by Demivan** [comment]
`fluent.js` inserts BiDi control codes based on the bundle configuration.

```ts
const bundle = new FluentBundle(locale, {
  useIsolating: false, // Disable BiDI
})
```

But currently, it does not provide a way of disabling it per translation. So `fluent-vue` does not support this.

But there is an easy solution to replace control characters:

```ts
const text = 'Hello, \u{2068}World\u{2069}!' 
const nonBidiText = text.replaceAll('\u{2068}', '').replaceAll('\u{2069}', '')
```

@Tnze would that work for you?

Another solution would be to add a parameter to `fluent-vue` methods, directive and component to disable BiDi. But it would be doing `replaceAll` anyway, until `fluent.js` adds this functionality.

**Comment by Tnze** [comment]
Thanks for explaining!

Finally I will use these one: `.replaceAll(/\u2068|\u2069/g, '')`. It works for me.
